pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS = 'dockerhub-credentials'
    }

    stages {
        stage('Build Image') {
            steps {
                script {
                    image = docker.build("ahmedhesham301/weatherapp","-f docker/dockerfile .")
                }
            }
        }
        stage('push image') {
            steps {
                script {
                    docker.withRegistry('', DOCKERHUB_CREDENTIALS) {
                        image.push("1.0")
                    }
                }
            }
        }
        stage("Terraform"){
            environment {
                aws_credentials = credentials('aws-credentials')
            }
            steps{
                withEnv([
                    "AWS_ACCESS_KEY_ID=${aws_credentials_USR}",
                    "AWS_SECRET_ACCESS_KEY=${aws_credentials_PSW}"
                ]){
                    sh'''
                        terraform -chdir=./terraform init
                        terraform -chdir=./terraform apply -auto-approve
                        terraform -chdir=./terraform output -json > terraform/output.json
                    '''
                }
            }
        }
        stage('Run ansible playbook') {
            steps {
                script {
                    withCredentials([
                        usernamePassword(credentialsId: DOCKERHUB_CREDENTIALS, usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PSW'),
                        string(credentialsId: 'open_weather_api_key' , variable: 'open_weather_api_key'),
                        sshUserPrivateKey(keyFileVariable:"sshKey", credentialsId:"aws-ssh-key")
                        ]) {
                        
                        sh """
                        chmod +x ansible/inventory.py
                        ./ansible/inventory.py --list > test.json
                        ansible-playbook -i ansible/inventory.py ansible/webservers.yaml \\
                        --extra-vars 'dockerhub_psw=$DOCKERHUB_PSW open_weather_api_key=$open_weather_api_key'
                        """
                    }
                }
            }
        }
        
    }
    // post{
    //     failure {
    //     mail bcc: '', body: 'pipeline failed', cc: '', from: '', replyTo: '', subject: 'pipeline failed', to: 'ahmed.hesham.farag@gmail.com'
    //     }
    //     success {
    //     mail bcc: '', body: 'pipeline succeed', cc: '', from: '', replyTo: '', subject: 'pipeline succeed', to: 'ahmed.hesham.farag@gmail.com'
    //     }
    // }
}
