---

- name: Setup webservers
  hosts: webservers
  become: true
  tasks:
   - name: Install docker
     ansible.builtin.yum:
      name: docker
      state: present
   - name: Start docker
     ansible.builtin.service:
      name: docker
      state: started
      enabled: true
   - name: Log into DockerHub
     community.docker.docker_login:
      username: ahmedhesham301
      password: ""
   - name: Pull the image
     community.docker.docker_image_pull:
      name: ahmedhesham301/weatherapp:1.0
   - name: Create a data container
     community.docker.docker_container:
      name: app
      image: ahmedhesham301/weatherapp:1.0
      state: started
      ports:
       - 5000:5000
      detach: true
